from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(727, 489)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left = QtWidgets.QFrame(Main)
        self.frame_left.setEnabled(True)
        self.frame_left.setMinimumSize(QtCore.QSize(120, 0))
        self.frame_left.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_profil = QtWidgets.QFrame(self.frame_left)
        self.frame_profil.setMinimumSize(QtCore.QSize(110, 110))
        self.frame_profil.setMaximumSize(QtCore.QSize(120, 110))
        self.frame_profil.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_profil.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_profil.setObjectName("frame_profil")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_profil)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2.addWidget(self.frame_profil)
        self.frame_daftartabel = QtWidgets.QFrame(self.frame_left)
        self.frame_daftartabel.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_daftartabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_daftartabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_daftartabel.setObjectName("frame_daftartabel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_daftartabel)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_home = QtWidgets.QPushButton(self.frame_daftartabel)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_3.addWidget(self.btn_home)
        self.lbl_daftartbl = QtWidgets.QLabel(self.frame_daftartabel)
        self.lbl_daftartbl.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_daftartbl.setFont(font)
        self.lbl_daftartbl.setObjectName("lbl_daftartbl")
        self.verticalLayout_3.addWidget(self.lbl_daftartbl)
        self.btn_balita = QtWidgets.QPushButton(self.frame_daftartabel)
        self.btn_balita.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_balita.setObjectName("btn_balita")
        self.verticalLayout_3.addWidget(self.btn_balita)
        self.btn_bumil = QtWidgets.QPushButton(self.frame_daftartabel)
        self.btn_bumil.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_bumil.setObjectName("btn_bumil")
        self.verticalLayout_3.addWidget(self.btn_bumil)
        self.btn_bidan = QtWidgets.QPushButton(self.frame_daftartabel)
        self.btn_bidan.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_bidan.setObjectName("btn_bidan")
        self.verticalLayout_3.addWidget(self.btn_bidan)
        self.btn_vit = QtWidgets.QPushButton(self.frame_daftartabel)
        self.btn_vit.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_vit.setObjectName("btn_vit")
        self.verticalLayout_3.addWidget(self.btn_vit)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.btn_keluar = QtWidgets.QPushButton(self.frame_daftartabel)
        self.btn_keluar.setObjectName("btn_keluar")
        self.verticalLayout_3.addWidget(self.btn_keluar)
        self.verticalLayout_2.addWidget(self.frame_daftartabel)
        self.horizontalLayout.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(Main)
        self.frame_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_header1 = QtWidgets.QFrame(self.frame_right)
        self.frame_header1.setMinimumSize(QtCore.QSize(0, 75))
        self.frame_header1.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_header1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_header1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_header1.setObjectName("frame_header1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_header1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_header = QtWidgets.QLabel(self.frame_header1)
        self.lbl_header.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lbl_header.setFont(font)
        self.lbl_header.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")
        self.verticalLayout_4.addWidget(self.lbl_header)
        self.verticalLayout.addWidget(self.frame_header1)
        self.frame_tabel1 = QtWidgets.QFrame(self.frame_right)
        self.frame_tabel1.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_tabel1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_tabel1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabel1.setObjectName("frame_tabel1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_tabel1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbl_home = QtWidgets.QLabel(self.frame_tabel1)
        self.lbl_home.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_home.setFont(font)
        self.lbl_home.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_home.setObjectName("lbl_home")
        self.verticalLayout_6.addWidget(self.lbl_home)
        self.frame_tabel2 = QtWidgets.QFrame(self.frame_tabel1)
        self.frame_tabel2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tabel2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tabel2.setObjectName("frame_tabel2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_tabel2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lbl_welcome = QtWidgets.QLabel(self.frame_tabel2)
        self.lbl_welcome.setMinimumSize(QtCore.QSize(0, 75))
        self.lbl_welcome.setMaximumSize(QtCore.QSize(16777215, 75))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lbl_welcome.setFont(font)
        self.lbl_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_welcome.setObjectName("lbl_welcome")
        self.verticalLayout_7.addWidget(self.lbl_welcome)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.btn_mulai = QtWidgets.QPushButton(self.frame_tabel2)
        self.btn_mulai.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_mulai.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.btn_mulai.setObjectName("btn_mulai")
        self.verticalLayout_7.addWidget(self.btn_mulai)
        self.btn_laporan = QtWidgets.QPushButton(self.frame_tabel2)
        self.btn_laporan.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_laporan.setObjectName("btn_laporan")
        self.verticalLayout_7.addWidget(self.btn_laporan)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.verticalLayout_6.addWidget(self.frame_tabel2)
        self.verticalLayout.addWidget(self.frame_tabel1)
        self.horizontalLayout.addWidget(self.frame_right)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Form"))
        self.btn_home.setText(_translate("Main", "Home"))
        self.lbl_daftartbl.setText(_translate("Main", "Informasi"))
        self.btn_balita.setText(_translate("Main", "Balita"))
        self.btn_bumil.setText(_translate("Main", "Ibu Hamil"))
        self.btn_bidan.setText(_translate("Main", "Bidan"))
        self.btn_vit.setText(_translate("Main", "Vitamin dan Obat"))
        self.btn_keluar.setText(_translate("Main", "Keluar"))
        self.lbl_header.setText(_translate("Main", "POSYANDU UNGU"))
        self.lbl_home.setText(_translate("Main", "Home"))
        self.lbl_welcome.setText(_translate("Main", "Selamat Datang"))
        self.btn_mulai.setText(_translate("Main", "Mulai Pelayanan"))
        self.btn_laporan.setText(_translate("Main", "Histori Laporan Pelayanan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QWidget()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
